version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: SampleDataGenerator.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: m/HCKWefqM4C3LsfGn8DvC7F06m5EDUBzJW9oP7NGEnK752IMmcCGysaqJvC4uIY
  on:
    branch: master