version: 1.0.{build}

# Do not build on tags (GitHub only)
skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  COVERALLS_REPO_TOKEN:
    secure: 4hr9SMmxg+bbvY0LAQZ8hCJ8i+AIaofGZBST4FYJSxqSP3CoLsn8KY3dnWAmNYNz
  COVERITY_TOKEN:
    secure: 3ynsUdboC/OKI8c/LJsjExqNeytf6wMCGGMqk8+KRis=
  COVERITY_EMAIL:
    secure: 6TqNM8aAZF3nLCV8ku1qCtKjb6qCFzCzv6aERdnFsVE=

install:
- ps: |
    $Env:RUN_COVERITY = $True
    Write-Host "RUN_COVERITY = " -NoNewLine
    Write-Host $Env:RUN_COVERITY -ForegroundColor "Green"

    If ($Env:RUN_COVERITY -eq $True)
    {
      cinst curl -y
    }

build:
  project: Build.proj
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

after_test:
- ps: |
    
    If ($Env:RUN_COVERITY -eq $True)
    {
      7z a "$Env:APPVEYOR_BUILD_FOLDER\$Env:APPVEYOR_PROJECT_NAME.zip" "$Env:APPVEYOR_BUILD_FOLDER\cov-int\"

      # cf. http://stackoverflow.com/a/25045154/335418
      Remove-item alias:curl

      Write-Host "Uploading Coverity analysis result..." -ForegroundColor "Green"

      curl --silent --show-error `
        --output curl-out.txt `
        --form token="$Env:coverity_token" `
        --form email="$Env:coverity_email" `
        --form "file=@$Env:APPVEYOR_BUILD_FOLDER\$Env:APPVEYOR_PROJECT_NAME.zip" `
        --form version="$Env:APPVEYOR_REPO_COMMIT" `
        --form description="CI server scheduled build." `
        https://scan.coverity.com/builds?project=mathieubrun%2FSampleDataGenerator

        cat .\curl-out.txt
    }
deploy:
- provider: NuGet
  api_key:
    secure: m/HCKWefqM4C3LsfGn8DvC7F06m5EDUBzJW9oP7NGEnK752IMmcCGysaqJvC4uIY
  on:
    branch: master