namespace SampleDataGenerator
{
    public static class StaticData
    {
        /// <summary>
        /// First names
        /// </summary>
        public static readonly string[] FirstNames = { "Adrien", "Agathe", "Alexandre", "Alexia", "Alexis", "Alice", "Alicia", "Amandine", "Amelie", "Anais", "Anthony", "Antoine", "Arthur", "Audrey", "Aurelien", "Axel", "Baptiste", "Bastien", "Benjamin", "Bryan", "Camille", "Carla", "Cassandra", "Celia", "Charlotte", "Chloe", "Claire", "Clara", "Clemence", "Clement", "Coralie", "Corentin", "Damien", "David", "Dorian", "Dylan", "Elisa", "Elise", "Elodie", "Emilie", "Emma", "Enzo", "Estelle", "Eva", "Fanny", "Florian", "Gabriel", "Guillaume", "Hugo", "Ines", "Jade", "Jeanne", "Jeremy", "Jordan", "Jules", "Julie", "Julien", "Juliette", "Justine", "Kevin", "Killian", "Laura", "Laurie", "Laurine", "Lea", "Lena", "Leo", "Lisa", "Loic", "Lola", "Louis", "Louise", "Lucas", "Lucie", "Maeva", "Manon", "Margaux", "Margot", "Marie", "Marine", "Marion", "Martin", "Mathieu", "Mathilde", "Mathis", "Matthieu", "Maxence", "Maxime", "Melanie", "Melissa", "Morgane", "Nathan", "Nicolas", "Noemie", "Oceane", "Paul", "Pauline", "Perrot", "Pierre", "Quentin", "Raphael", "Remi", "Romain", "Romane", "Samuel", "Sarah", "Simon", "Solene", "Theo", "Thibault", "Thomas", "Tom", "Tristan", "Valentin", "Valentine", "Victor", "Vincent", "William", "Yanis", "Yann", "Zoe" };

        /// <summary>
        /// Last names
        /// </summary>
        public static readonly string[] LastNames = { "Adam", "Andre", "Arnaud", "Aubert", "Aubry", "Bailly", "Barbier", "Barre", "Benoit", "Berger", "Bernard", "Bertin", "Bertrand", "Blanc", "Blanchar", "Bonnet", "Boucher", "Bouchet", "Bourgeois", "Bouvier", "Boyer", "Breton", "Brun", "Brunet", "Caron", "Carpentier", "Carre", "Charles", "Charpentier", "Chevalier", "Clement", "Colin", "Collet", "Collin", "Cousin", "David", "Deschamps", "Dubois", "Dufour", "Dumont", "Dupont", "Dupuis", "Dupuy", "Durand", "Duval", "Etienne", "Fabre", "Fernandez", "Fontaine", "Fournier", "Francois", "Gaillard", "Garcia", "Garnier", "Gauthier", "Gautier", "Gerard", "Germain", "Girard", "Giraud", "Gonzalez", "Guerin", "Guillaume", "Guillot", "Guyot", "Henry", "Herve", "Hubert", "Huet", "Humbert", "Jacob", "Jacquet", "Jean", "Joly", "Klein", "Lambert", "Laurent", "Le gall", "Le goff", "Le roux", "Leblanc", "Lebrun", "Leclercq", "Lecomte", "Lefebvre", "Lefevre", "Leger", "Legrand", "Lemaire", "Lemoine", "Leroux", "Leroy", "Lesage", "Leveque", "Lopez", "Louis", "Lucas", "Maillard", "Marchal", "Marchand", "Martin", "Masson", "Mathieu", "Menard", "Mercier", "Meunier", "Meyer", "Michel", "Millet", "Moreau", "Morel", "Moulin", "Nguyen", "Nicolas", "Noel", "Olivier", "Pelletier", "Perez", "Perrier", "Perrin", "Perrot", "Petit", "Philippe", "Picard", "Pierre", "Poirier", "Prevost", "Remy", "Renard", "Renaud", "Renault", "Rey", "Riviere", "Robert", "Robin", "Rodriguez", "Rolland", "Rousseau", "Roussel", "Roux", "Roy", "Royer", "Sanchez", "Schmitt", "Simon", "Tessier", "Thomas", "Vasseur", "Vidal", "Weber" };

        /// <summary>
        /// Company names
        /// </summary>
        /// <remarks>
        /// from http://brendoman.com/media/users/dan/finctional_companies.txt
        /// </remarks>
        public static readonly string[] Companies = { "123 Warehousing", "ABC Telecom", "Acme Corp", "Acme, inc.", "Ajax", "Allied Biscuit", "Ankh-Sto Associates", "Atlantic Northern", "Axis Chemical Co.", "Barrytron", "Big Kahuna Burger", "Big T Burgers and Fries", "Blammo", "BLAND Corporation", "Bluth Company", "Burleigh and Stronginthearm", "C.H. Lavatory and Sons", "Carrys Candles", "Central Perk", "Charles Townsend Agency", "Chasers", "Chez Quis", "Chotchkies", "Cogswell Cogs", "Colonial Movers", "Compuglobalhypermeganet", "Corellian Engineering Corporation", "Data Systems", "Demo Company", "Demo, inc.", "Duff Brewing Company", "Dunder Mifflin", "Extensive Enterprise", "Fake Brothers", "Flowers By Irene", "Foo Bars", "Gadgetron", "Galaxy Corp", "General Forge and Foundry", "General Products", "General Services Corporation", "Gizmonic Institute", "Globex Corporation", "Globo Gym American Corp", "Globo-Chem", "Gringotts", "Incom Corporation", "Industrial Automation", "Initech", "Initrode", "Input, Inc.", "Keedsler Motors", "Klimpys", "Krustyco", "Kumatsu Motors", "Leeding Engines Ltd.", "LexCorp", "LuthorCorp", "Mainway Toys", "Mammoth Pictures", "McMahon and Tate", "Megadodo Publications", "Milliways", "Minuteman Cafe", "Moes Tavern", "Monarch Playing Card Co.", "Monks Diner", "Mooby Corp", "Mr. Sparkle", "Niagular", "Nordyne Defense Dynamics", "North Central Positronics", "Omni Consimer Products", "Osato Chemicals", "Petrox Oil Company", "Plow King", "Powell Motors", "Praxis Corporation", "Primatech", "QWERTY Logistics", "Roboto Industries", "Rouster and Sideways", "Roxxon", "Sample Company", "Sample, inc", "Sirius Cybernetics Corporation", "Sixty Second Avenue", "Smith and Co.", "Sombra Corporation", "Sonky Rubber Goods", "Spacely Sprockets", "Spade and Archer", "SpringShield", "St. Anky Beer", "Stay Puft Corporation", "Sto Plains Holdings", "Strickland Propane", "Taco Grande", "Taggart Transcontinental", "Tessier-Ashpool", "Thatherton Fuels", "The Frying Dutchman", "The Krusty Krab", "The Legitimate Businessmens Club", "The New Firm", "Three Waters", "Thrift Bank", "Tip Top Cafe", "Transworld Consortium", "U.S. Robotics and Mechanical Men", "United Fried Chicken", "Universal Export", "Vandelay Industries", "Videlectrix", "Virtucon", "Water and Power", "Wayne Enterprises", "Wentworth Industries", "Wernham Hogg", "Western Gas & Electric", "Widget Corp", "Zevo Toys", "ZiffCorp" };

        /// <summary>
        /// Countries
        /// </summary>
        /// <remarks>
        /// from http://www.state.gov/misc/list/
        /// </remarks>
        public static readonly string[] Countries = { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas, The", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei ", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Curacao", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia, The", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territories", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa ", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain ", "Sri Lanka", "Sudan", "Suriname", "Swaziland ", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand ", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe" };
    }
}